import { NextResponse } from "next/server"
import { sql } from "@/lib/db"

export async function POST() {
  try {
    // Limpar veículos existentes
    await sql`DELETE FROM vehicle_images`
    await sql`DELETE FROM vehicles`

    // Buscar IDs de categorias e marcas
    const [sedans] = await sql`SELECT id FROM vehicle_categories WHERE slug = 'sedans'`
    const [suvs] = await sql`SELECT id FROM vehicle_categories WHERE slug = 'suvs'`
    const [hatchbacks] = await sql`SELECT id FROM vehicle_categories WHERE slug = 'hatchbacks'`

    const [toyota] = await sql`SELECT id FROM brands WHERE slug = 'toyota'`
    const [honda] = await sql`SELECT id FROM brands WHERE slug = 'honda'`
    const [vw] = await sql`SELECT id FROM brands WHERE slug = 'volkswagen'`
    const [chevrolet] = await sql`SELECT id FROM brands WHERE slug = 'chevrolet'`
    const [fiat] = await sql`SELECT id FROM brands WHERE slug = 'fiat'`
    const [ford] = await sql`SELECT id FROM brands WHERE slug = 'ford'`
    const [volkswagen] = await sql`SELECT id FROM brands WHERE slug = 'volkswagen'` // Declare volkswagen variable

    // SEDANS
    const vehicles = [
      {
        brand_id: toyota.id,
        category_id: sedans.id,
        name: "Toyota Corolla XEi 2.0",
        slug: "toyota-corolla-xei-2024",
        model: "Corolla XEi",
        year: 2024,
        price: 145900.0,
        mileage: 0,
        color: "Prata",
        fuel_type: "Flex",
        transmission: "Automático CVT",
        engine: "2.0 16V",
        description: "Sedan médio mais vendido do Brasil com conforto, economia e tecnologia de ponta.",
        features: [
          "Central multimídia 9 pol",
          "Câmera de ré",
          "Sensor de estacionamento",
          "Controle de cruzeiro",
          "Ar digital",
          "Bancos em couro",
          "Faróis LED",
        ],
        specifications: { portas: 4, airbags: 7, porta_malas: "470L", consumo: "14 km/l" },
        status: "available",
        is_featured: true,
        is_new: true,
        published: true,
        images: ["/vehicles/sedan-toyota-corolla.jpg"],
      },
      {
        brand_id: honda.id,
        category_id: sedans.id,
        name: "Honda Civic Touring",
        slug: "honda-civic-touring-2024",
        model: "Civic Touring",
        year: 2024,
        price: 189900.0,
        mileage: 0,
        color: "Preto",
        fuel_type: "Gasolina",
        transmission: "Automático CVT",
        engine: "1.5 Turbo",
        description: "Design arrojado e motor turbo potente. O sedan mais desejado da categoria premium.",
        features: [
          "Motor turbo 173cv",
          "Teto solar panorâmico",
          "Sistema Honda Sensing",
          "Painel digital 10.2",
          "Carregador wireless",
        ],
        specifications: { portas: 4, airbags: 6, porta_malas: "519L", consumo: "13 km/l" },
        status: "available",
        is_featured: true,
        is_new: true,
        published: true,
        images: ["/vehicles/sedan-honda-civic.jpg"],
      },
      {
        brand_id: vw.id,
        category_id: sedans.id,
        name: "Volkswagen Jetta GLi",
        slug: "vw-jetta-gli-2024",
        model: "Jetta GLi",
        year: 2024,
        price: 167900.0,
        mileage: 0,
        color: "Branco",
        fuel_type: "Gasolina",
        transmission: "Automático",
        engine: "1.4 TSI",
        description: "Sedan alemão com tecnologia avançada e design sofisticado.",
        features: ["Tela 10 pol", "VW Play", "Faróis Full LED", "Controle de cruzeiro", "Câmera 360°"],
        specifications: { portas: 4, airbags: 6, porta_malas: "510L" },
        status: "available",
        is_featured: false,
        is_new: true,
        published: true,
        images: ["/vehicles/sedan-vw-jetta.jpg"],
      },
      {
        brand_id: chevrolet.id,
        category_id: sedans.id,
        name: "Chevrolet Onix Plus Premier",
        slug: "chevrolet-onix-plus-2024",
        model: "Onix Plus Premier",
        year: 2024,
        price: 98900.0,
        mileage: 0,
        color: "Vermelho",
        fuel_type: "Flex",
        transmission: "Automático",
        engine: "1.0 Turbo",
        description: "Sedan compacto mais moderno do Brasil com motor turbo eficiente.",
        features: ["MyLink Plus 8 pol", "Ar automático", "Carregamento wireless", "Sensor crepuscular"],
        specifications: { portas: 4, airbags: 6, porta_malas: "469L" },
        status: "available",
        is_featured: false,
        is_new: true,
        published: true,
        images: ["/vehicles/sedan-chevrolet-onix.jpg"],
      },
      {
        brand_id: fiat.id,
        category_id: sedans.id,
        name: "Fiat Cronos Precision",
        slug: "fiat-cronos-precision-2023",
        model: "Cronos Precision",
        year: 2023,
        price: 82900.0,
        mileage: 15000,
        color: "Cinza",
        fuel_type: "Flex",
        transmission: "Automático GSR",
        engine: "1.8 16V",
        description: "Sedan italiano com ótimo custo-benefício. Seminovo perfeito.",
        features: ["Central Uconnect 7 pol", "Ar automático", "Direção elétrica"],
        specifications: { portas: 4, airbags: 4, porta_malas: "524L" },
        status: "available",
        is_featured: false,
        is_new: false,
        published: true,
        images: ["/vehicles/sedan-fiat-cronos.jpg"],
      },
      // SUVs
      {
        brand_id: toyota.id,
        category_id: suvs.id,
        name: "Toyota RAV4 Hybrid",
        slug: "toyota-rav4-hybrid-2024",
        model: "RAV4 Hybrid",
        year: 2024,
        price: 298900.0,
        mileage: 0,
        color: "Branco Pérola",
        fuel_type: "Híbrido",
        transmission: "Automático CVT",
        engine: "2.5 Híbrido",
        description: "SUV híbrido com tecnologia de ponta e máxima economia de combustível.",
        features: [
          "Sistema híbrido AWD",
          "Teto solar panorâmico",
          "Toyota Safety Sense",
          'Painel digital 12.3"',
          "Carregador wireless",
        ],
        specifications: { portas: 5, airbags: 8, porta_malas: "580L", consumo: "16 km/l" },
        status: "available",
        is_featured: true,
        is_new: true,
        published: true,
        images: ["/vehicles/suv-toyota-rav4.jpg"],
      },
      {
        brand_id: honda.id,
        category_id: suvs.id,
        name: "Honda CR-V Touring",
        slug: "honda-crv-touring-2024",
        model: "CR-V Touring",
        year: 2024,
        price: 268900.0,
        mileage: 0,
        color: "Cinza Grafite",
        fuel_type: "Gasolina",
        transmission: "Automático CVT",
        engine: "1.5 Turbo",
        description: "SUV premium com 7 lugares, espaço interno generoso e tecnologia completa.",
        features: [
          "Motor turbo 190cv",
          "7 lugares",
          "Honda Sensing",
          "Teto solar",
          "Bancos em couro",
          "Painel digital",
        ],
        specifications: { portas: 5, airbags: 6, porta_malas: "522L", consumo: "11 km/l" },
        status: "available",
        is_featured: true,
        is_new: true,
        published: true,
        images: ["/vehicles/suv-honda-crv.jpg"],
      },
      {
        brand_id: vw.id,
        category_id: suvs.id,
        name: "Volkswagen Tiguan Allspace",
        slug: "vw-tiguan-allspace-2024",
        model: "Tiguan Allspace",
        year: 2024,
        price: 248900.0,
        mileage: 0,
        color: "Azul Atlântico",
        fuel_type: "Gasolina",
        transmission: "Automático DSG",
        engine: "2.0 TSI",
        description: "SUV alemão com 7 lugares, design sofisticado e dirigibilidade esportiva.",
        features: [
          "7 lugares",
          "Tração 4Motion",
          'Tela 9.2"',
          "Cockpit digital",
          "Faróis LED matriz",
          "Estacionamento automático",
        ],
        specifications: { portas: 5, airbags: 7, porta_malas: "700L", consumo: "10 km/l" },
        status: "available",
        is_featured: false,
        is_new: true,
        published: true,
        images: ["/vehicles/suv-volkswagen-tiguan.jpg"],
      },
      {
        brand_id: chevrolet.id,
        category_id: suvs.id,
        name: "Chevrolet Tracker Premier",
        slug: "chevrolet-tracker-premier-2024",
        model: "Tracker Premier",
        year: 2024,
        price: 168900.0,
        mileage: 0,
        color: "Vermelho",
        fuel_type: "Flex",
        transmission: "Automático",
        engine: "1.0 Turbo",
        description: "SUV compacto moderno com excelente custo-benefício e tecnologia avançada.",
        features: [
          'MyLink Plus 10.2"',
          "Ar automático dual",
          "Teto solar elétrico",
          "Carregador wireless",
          "Câmera 360°",
        ],
        specifications: { portas: 5, airbags: 6, porta_malas: "401L", consumo: "13 km/l" },
        status: "available",
        is_featured: true,
        is_new: true,
        published: true,
        images: ["/vehicles/suv-chevrolet-tracker.jpg"],
      },
      {
        brand_id: ford.id,
        category_id: suvs.id,
        name: "Ford Territory Titanium",
        slug: "ford-territory-titanium-2024",
        model: "Territory Titanium",
        year: 2024,
        price: 189900.0,
        mileage: 0,
        color: "Prata",
        fuel_type: "Gasolina",
        transmission: "Automático CVT",
        engine: "1.5 Turbo",
        description: "SUV médio com design arrojado e recursos tecnológicos de última geração.",
        features: [
          'Tela vertical 12.3"',
          "SYNC 4",
          "Teto panorâmico",
          "Ar tri-zone",
          "Assistente de estacionamento",
          "7 modos de condução",
        ],
        specifications: { portas: 5, airbags: 6, porta_malas: "448L", consumo: "11 km/l" },
        status: "available",
        is_featured: false,
        is_new: true,
        published: true,
        images: ["/vehicles/suv-ford-territory.jpg"],
      },
      // HATCHBACKS
      {
        brand_id: volkswagen.id,
        category_id: hatchbacks.id,
        name: "Volkswagen Polo Track",
        slug: "vw-polo-track-2024",
        model: "Polo Track",
        year: 2024,
        price: 89900.0,
        mileage: 0,
        color: "Branco",
        fuel_type: "Flex",
        transmission: "Automático",
        engine: "1.0 TSI",
        description: "Hatchback compacto com tecnologia alemã e design moderno.",
        features: ['VW Play 10"', "Ar automático", "Sensor de estacionamento", "Controles no volante", "Faróis LED"],
        specifications: { portas: 5, airbags: 6, porta_malas: "300L", consumo: "14 km/l" },
        status: "available",
        is_featured: false,
        is_new: true,
        published: true,
        images: ["/vehicles/hatch-vw-polo.jpg"],
      },
      {
        brand_id: toyota.id,
        category_id: hatchbacks.id,
        name: "Toyota Yaris XLS",
        slug: "toyota-yaris-xls-2024",
        model: "Yaris XLS",
        year: 2024,
        price: 98900.0,
        mileage: 0,
        color: "Vermelho",
        fuel_type: "Flex",
        transmission: "Automático CVT",
        engine: "1.5 16V",
        description: "Hatchback premium com qualidade Toyota e design esportivo.",
        features: [
          'Central 9"',
          "Câmera de ré",
          "Ar automático",
          "Bancos em couro sintético",
          "Faróis LED",
          "Sensor de chuva",
        ],
        specifications: { portas: 5, airbags: 7, porta_malas: "286L", consumo: "15 km/l" },
        status: "available",
        is_featured: true,
        is_new: true,
        published: true,
        images: ["/vehicles/hatch-toyota-yaris.jpg"],
      },
      {
        brand_id: honda.id,
        category_id: hatchbacks.id,
        name: "Honda Fit EXL",
        slug: "honda-fit-exl-2023",
        model: "Fit EXL",
        year: 2023,
        price: 94900.0,
        mileage: 18000,
        color: "Cinza",
        fuel_type: "Flex",
        transmission: "Automático CVT",
        engine: "1.5 16V",
        description: "Hatchback versátil com banco mágico e espaço interno surpreendente.",
        features: ["Honda Connect", "Banco mágico", "Ar automático", "Câmera de ré", "Sensor de estacionamento"],
        specifications: { portas: 5, airbags: 6, porta_malas: "354L", consumo: "14 km/l" },
        status: "available",
        is_featured: false,
        is_new: false,
        published: true,
        images: ["/vehicles/hatch-honda-fit.jpg"],
      },
      {
        brand_id: chevrolet.id,
        category_id: hatchbacks.id,
        name: "Chevrolet Onix Premier",
        slug: "chevrolet-onix-premier-2024",
        model: "Onix Premier",
        year: 2024,
        price: 92900.0,
        mileage: 0,
        color: "Azul",
        fuel_type: "Flex",
        transmission: "Automático",
        engine: "1.0 Turbo",
        description: "Hatchback mais vendido do Brasil com motor turbo e tecnologia completa.",
        features: ['MyLink 8"', "Ar automático", "Carregamento wireless", "Sensor crepuscular", "Câmera de ré"],
        specifications: { portas: 5, airbags: 6, porta_malas: "303L", consumo: "15 km/l" },
        status: "available",
        is_featured: true,
        is_new: true,
        published: true,
        images: ["/vehicles/hatch-chevrolet-onix.jpg"],
      },
      {
        brand_id: fiat.id,
        category_id: hatchbacks.id,
        name: "Fiat Argo Trekking",
        slug: "fiat-argo-trekking-2024",
        model: "Argo Trekking",
        year: 2024,
        price: 87900.0,
        mileage: 0,
        color: "Laranja",
        fuel_type: "Flex",
        transmission: "Automático CVT",
        engine: "1.3",
        description: "Hatchback aventureiro com visual robusto e ótimo custo-benefício.",
        features: ['Uconnect 7"', "Ar digital", "Proteções laterais", 'Rodas 16"', "Retrovisores elétricos"],
        specifications: { portas: 5, airbags: 4, porta_malas: "300L", consumo: "13 km/l" },
        status: "available",
        is_featured: false,
        is_new: true,
        published: true,
        images: ["/vehicles/hatch-fiat-argo.jpg"],
      },
    ]

    // Inserir veículos
    for (const vehicle of vehicles) {
      const [insertedVehicle] = await sql`
        INSERT INTO vehicles (
          brand_id, category_id, name, slug, model, year, price, mileage, 
          color, fuel_type, transmission, engine, description, features, 
          specifications, status, is_featured, is_new, published, published_at
        ) VALUES (
          ${vehicle.brand_id}, ${vehicle.category_id}, ${vehicle.name}, 
          ${vehicle.slug}, ${vehicle.model}, ${vehicle.year}, ${vehicle.price}, 
          ${vehicle.mileage}, ${vehicle.color}, ${vehicle.fuel_type}, 
          ${vehicle.transmission}, ${vehicle.engine}, ${vehicle.description}, 
          ${JSON.stringify(vehicle.features)}, ${JSON.stringify(vehicle.specifications)}, 
          ${vehicle.status}, ${vehicle.is_featured}, ${vehicle.is_new}, 
          ${vehicle.published}, NOW()
        )
        RETURNING id
      `

      // Inserir imagens
      if (vehicle.images && vehicle.images.length > 0) {
        for (let i = 0; i < vehicle.images.length; i++) {
          await sql`
            INSERT INTO vehicle_images (vehicle_id, url, alt_text, display_order, is_primary)
            VALUES (
              ${insertedVehicle.id}, 
              ${vehicle.images[i]}, 
              ${vehicle.name}, 
              ${i}, 
              ${i === 0}
            )
          `
        }
      }
    }

    return NextResponse.json({
      success: true,
      message: `${vehicles.length} veículos adicionados com sucesso!`,
    })
  } catch (error: any) {
    console.error("[v0] Erro ao popular veículos:", error)
    return NextResponse.json({ success: false, error: error.message }, { status: 500 })
  }
}
